# This file is auto-generated from the current state of the database. Instead
# of editing this file, please use the migrations feature of Active Record to
# incrementally modify your database, and then regenerate this schema definition.
#
# This file is the source Rails uses to define your schema when running `bin/rails
# db:schema:load`. When creating a new database, `bin/rails db:schema:load` tends to
# be faster and is potentially less error prone than running all of your
# migrations from scratch. Old migrations may fail to apply correctly if those
# migrations use external dependencies or application code.
#
# It's strongly recommended that you check this file into your version control system.

ActiveRecord::Schema.define(version: 2024_01_28_160551) do

  # These are extensions that must be enabled in order to support this database
  enable_extension "plpgsql"

  create_table "auths", force: :cascade do |t|
    t.string "user_name"
    t.string "role"
    t.string "password_digest"
    t.datetime "created_at", precision: 6, null: false
    t.datetime "updated_at", precision: 6, null: false
  end

  create_table "completed_trucks", force: :cascade do |t|
    t.string "regnumber"
    t.datetime "time"
    t.datetime "created_at", precision: 6, null: false
    t.datetime "updated_at", precision: 6, null: false
    t.date "date"
    t.string "spare"
    t.string "status"
    t.datetime "completed_at"
  end

  create_table "finaltables", force: :cascade do |t|
    t.string "startPosition"
    t.string "startTime"
    t.string "endLocation"
    t.string "startLocation1"
    t.string "startLocation2"
    t.string "startLocation3"
    t.string "startLocation4"
    t.string "startLocation5"
    t.string "startLocation6"
    t.string "startLocation7"
    t.string "startLocation8"
    t.string "startLocation9"
    t.string "startLocation10"
    t.string "startLocation11"
    t.string "startLocation12"
    t.string "startLocation13"
    t.string "startLocation14"
    t.string "startLocation15"
    t.string "startLocation16"
    t.string "startLocation17"
    t.string "startLocation18"
    t.string "endLocation1"
    t.string "endLocation2"
    t.string "endLocation3"
    t.string "endLocation4"
    t.string "endLocation5"
    t.string "endLocation6"
    t.string "endLocation7"
    t.string "endLocation8"
    t.string "endLocation9"
    t.string "endLocation10"
    t.string "endLocation11"
    t.string "endLocation12"
    t.string "endLocation13"
    t.string "endLocation14"
    t.string "endLocation15"
    t.string "endLocation16"
    t.string "endLocation17"
    t.string "endLocation18"
    t.string "startTime1"
    t.string "startTime2"
    t.string "startTime3"
    t.string "startTime4"
    t.string "startTime5"
    t.string "startTime6"
    t.string "startTime7"
    t.string "startTime8"
    t.string "startTime9"
    t.string "startTime10"
    t.string "startTime11"
    t.string "startTime12"
    t.string "startTime13"
    t.string "startTime14"
    t.string "startTime15"
    t.string "startTime16"
    t.string "startTime17"
    t.string "startTime18"
    t.string "endTime1"
    t.string "endTime2"
    t.string "endTime3"
    t.string "endTime4"
    t.string "endTime5"
    t.string "endTime6"
    t.string "endTime7"
    t.string "endTime8"
    t.string "endTime9"
    t.string "endTime10"
    t.string "endTime11"
    t.string "endTime12"
    t.string "endTime13"
    t.string "endTime14"
    t.string "endTime15"
    t.string "endTime16"
    t.string "endTime17"
    t.string "endTime18"
    t.string "driveTime1"
    t.string "driveTime2"
    t.string "driveTime3"
    t.string "driveTime4"
    t.string "driveTime5"
    t.string "driveTime6"
    t.string "driveTime7"
    t.string "driveTime8"
    t.string "driveTime9"
    t.string "driveTime10"
    t.string "driveTime11"
    t.string "driveTime12"
    t.string "driveTime13"
    t.string "driveTime14"
    t.string "driveTime15"
    t.string "driveTime16"
    t.string "driveTime17"
    t.string "driveTime18"
    t.string "event1"
    t.string "event2"
    t.string "event3"
    t.string "event4"
    t.string "event5"
    t.string "event6"
    t.string "event7"
    t.string "event8"
    t.string "event9"
    t.string "event10"
    t.string "event11"
    t.string "event12"
    t.string "event13"
    t.string "event14"
    t.string "event15"
    t.string "event16"
    t.string "event17"
    t.string "event18"
    t.integer "distance1"
    t.integer "distance2"
    t.integer "distance3"
    t.integer "distance4"
    t.integer "distance5"
    t.integer "distance6"
    t.integer "distance7"
    t.integer "distance8"
    t.integer "distance9"
    t.integer "distance10"
    t.integer "distance11"
    t.integer "distance12"
    t.integer "distance13"
    t.integer "distance14"
    t.integer "distance15"
    t.integer "distance16"
    t.integer "distance17"
    t.integer "distance18"
    t.datetime "created_at", precision: 6, null: false
    t.datetime "updated_at", precision: 6, null: false
  end

  create_table "finaltemplates", force: :cascade do |t|
    t.string "startPosition"
    t.string "startTime"
    t.string "endLocation"
    t.string "startLocation1"
    t.string "startLocation2"
    t.string "startLocation3"
    t.string "startLocation4"
    t.string "startLocation5"
    t.string "startLocation6"
    t.string "startLocation7"
    t.string "startLocation8"
    t.string "startLocation9"
    t.string "startLocation10"
    t.string "startLocation11"
    t.string "startLocation12"
    t.string "startLocation13"
    t.string "startLocation14"
    t.string "startLocation15"
    t.string "startLocation16"
    t.string "startLocation17"
    t.string "startLocation18"
    t.string "endLocation1"
    t.string "endLocation2"
    t.string "endLocation3"
    t.string "endLocation4"
    t.string "endLocation5"
    t.string "endLocation6"
    t.string "endLocation7"
    t.string "endLocation8"
    t.string "endLocation9"
    t.string "endLocation10"
    t.string "endLocation11"
    t.string "endLocation12"
    t.string "endLocation13"
    t.string "endLocation14"
    t.string "endLocation15"
    t.string "endLocation16"
    t.string "endLocation17"
    t.string "endLocation18"
    t.string "startTime1"
    t.string "startTime2"
    t.string "startTime3"
    t.string "startTime4"
    t.string "startTime5"
    t.string "startTime6"
    t.string "startTime7"
    t.string "startTime8"
    t.string "startTime9"
    t.string "startTime10"
    t.string "startTime11"
    t.string "startTime12"
    t.string "startTime13"
    t.string "startTime14"
    t.string "startTime15"
    t.string "startTime16"
    t.string "startTime17"
    t.string "startTime18"
    t.string "endTime1"
    t.string "endTime2"
    t.string "endTime3"
    t.string "endTime4"
    t.string "endTime5"
    t.string "endTime6"
    t.string "endTime7"
    t.string "endTime8"
    t.string "endTime9"
    t.string "endTime10"
    t.string "endTime11"
    t.string "endTime12"
    t.string "endTime13"
    t.string "endTime14"
    t.string "endTime15"
    t.string "endTime16"
    t.string "endTime17"
    t.string "endTime18"
    t.string "driveTime1"
    t.string "driveTime2"
    t.string "driveTime3"
    t.string "driveTime4"
    t.string "driveTime5"
    t.string "driveTime6"
    t.string "driveTime7"
    t.string "driveTime8"
    t.string "driveTime9"
    t.string "driveTime10"
    t.string "driveTime11"
    t.string "driveTime12"
    t.string "driveTime13"
    t.string "driveTime14"
    t.string "driveTime15"
    t.string "driveTime16"
    t.string "driveTime17"
    t.string "driveTime18"
    t.string "event1"
    t.string "event2"
    t.string "event3"
    t.string "event4"
    t.string "event5"
    t.string "event6"
    t.string "event7"
    t.string "event8"
    t.string "event9"
    t.string "event10"
    t.string "event11"
    t.string "event12"
    t.string "event13"
    t.string "event14"
    t.string "event15"
    t.string "event16"
    t.string "event17"
    t.string "event18"
    t.integer "distance1"
    t.integer "distance2"
    t.integer "distance3"
    t.integer "distance4"
    t.integer "distance5"
    t.integer "distance6"
    t.integer "distance7"
    t.integer "distance8"
    t.integer "distance9"
    t.integer "distance10"
    t.integer "distance11"
    t.integer "distance12"
    t.integer "distance13"
    t.integer "distance14"
    t.integer "distance15"
    t.integer "distance16"
    t.integer "distance17"
    t.integer "distance18"
    t.datetime "created_at", precision: 6, null: false
    t.datetime "updated_at", precision: 6, null: false
  end

  create_table "maintenances", force: :cascade do |t|
    t.string "regnumber"
    t.date "date"
    t.datetime "time"
    t.string "spare"
    t.datetime "created_at", precision: 6, null: false
    t.datetime "updated_at", precision: 6, null: false
    t.string "status", default: "Under Maintenance"
  end

  create_table "newtemplates", force: :cascade do |t|
    t.string "startPosition"
    t.string "startTime"
    t.string "endLocation"
    t.string "startLocation1"
    t.string "startLocation2"
    t.string "startLocation3"
    t.string "startLocation4"
    t.string "startLocation5"
    t.string "startLocation6"
    t.string "startLocation7"
    t.string "startLocation8"
    t.string "startLocation9"
    t.string "startLocation10"
    t.string "startLocation11"
    t.string "startLocation12"
    t.string "startLocation13"
    t.string "startLocation14"
    t.string "startLocation15"
    t.string "startLocation16"
    t.string "startLocation17"
    t.string "startLocation18"
    t.string "endLocation1"
    t.string "endLocation2"
    t.string "endLocation3"
    t.string "endLocation4"
    t.string "endLocation5"
    t.string "endLocation6"
    t.string "endLocation7"
    t.string "endLocation8"
    t.string "endLocation9"
    t.string "endLocation10"
    t.string "endLocation11"
    t.string "endLocation12"
    t.string "endLocation13"
    t.string "endLocation14"
    t.string "endLocation15"
    t.string "endLocation16"
    t.string "endLocation17"
    t.string "endLocation18"
    t.string "startTime1"
    t.string "startTime2"
    t.string "startTime3"
    t.string "startTime4"
    t.string "startTime5"
    t.string "tartTime6"
    t.string "startTime7"
    t.string "startTime8"
    t.string "startTime9"
    t.string "startTime10"
    t.string "startTime11"
    t.string "startTime12"
    t.string "startTime13"
    t.string "startTime14"
    t.string "startTime15"
    t.string "startTime16"
    t.string "startTime17"
    t.string "startTime18"
    t.string "endTime1"
    t.string "endTime2"
    t.string "endTime3"
    t.string "endTime4"
    t.string "endTime5"
    t.string "endTime6"
    t.string "endTime7"
    t.string "endTime8"
    t.string "endTime9"
    t.string "endTime10"
    t.string "endTime11"
    t.string "endTime12"
    t.string "endTime13"
    t.string "endTime14"
    t.string "endTime15"
    t.string "endTime16"
    t.string "endTime17"
    t.string "endTime18"
    t.string "driveTime1"
    t.string "driveTime2"
    t.string "driveTime3"
    t.string "driveTime4"
    t.string "driveTime5"
    t.string "driveTime6"
    t.string "driveTime7"
    t.string "driveTime8"
    t.string "driveTime9"
    t.string "driveTime10"
    t.string "driveTime11"
    t.string "driveTime12"
    t.string "driveTime13"
    t.string "driveTime14"
    t.string "driveTime15"
    t.string "driveTime16"
    t.string "driveTime17"
    t.string "driveTime18"
    t.string "event1"
    t.string "event2"
    t.string "event3"
    t.string "event4"
    t.string "event5"
    t.string "event6"
    t.string "event7"
    t.string "event8"
    t.string "event9"
    t.string "event10"
    t.string "event11"
    t.string "event12"
    t.string "event13"
    t.string "event14"
    t.string "event15"
    t.string "event16"
    t.string "event17"
    t.string "event18"
    t.integer "distance1"
    t.integer "distance2"
    t.integer "distance3"
    t.integer "distance4"
    t.integer "distance5"
    t.integer "distance6"
    t.integer "distance7"
    t.integer "distance8"
    t.integer "distance9"
    t.integer "distance10"
    t.integer "distance11"
    t.integer "distance12"
    t.integer "distance13"
    t.integer "distance14"
    t.integer "distance15"
    t.integer "distance16"
    t.integer "distance17"
    t.integer "distance18"
    t.datetime "created_at", precision: 6, null: false
    t.datetime "updated_at", precision: 6, null: false
  end

  create_table "templates", force: :cascade do |t|
    t.date "date"
    t.text "start_location"
    t.text "stop_location"
    t.text "start_time"
    t.text "stop_time"
    t.text "event"
    t.datetime "created_at", precision: 6, null: false
    t.datetime "updated_at", precision: 6, null: false
  end

end
